"""Fix NCAAB team abbreviations using SSOT dictionary.

Replaces garbage derived abbreviations (e.g., "ACT" for Alabama, "DBD" for
Duke, "KWI" for Kentucky) with recognizable broadcast-standard abbreviations
(ALA, DUKE, UK). Also updates short_name to match canonical names.

Matches teams by cbb_team_id in external_codes JSONB for reliability.
Teams without a cbb_team_id match are logged for manual review.

Revision ID: 20260211_000001
Revises: 20260208_000001
Create Date: 2026-02-11
"""

from __future__ import annotations

from alembic import op
from sqlalchemy import text

revision = "20260211_000001"
down_revision = "20260208_000001"
branch_labels = None
depends_on = None

# (canonical_name, abbreviation, cbb_team_id)
# Must stay in sync with scraper/sports_scraper/normalization/ncaab_teams.py
_NCAAB_TEAMS: list[tuple[str, str, int]] = [
    ("Abilene Christian Wildcats", "ACU", 1),
    ("Air Force Falcons", "AF", 2),
    ("Akron Zips", "AKR", 3),
    ("Alabama Crimson Tide", "ALA", 5),
    ("Alabama St Hornets", "ALST", 6),
    ("Albany Great Danes", "ALB", 306),
    ("Alcorn St Braves", "ALC", 7),
    ("American Eagles", "AMER", 8),
    ("Appalachian St Mountaineers", "APP", 9),
    ("Arizona St Sun Devils", "ASU", 10),
    ("Arizona Wildcats", "ARIZ", 11),
    ("Arkansas Razorbacks", "ARK", 12),
    ("Arkansas St Red Wolves", "ARST", 13),
    ("Arkansas-Little Rock Trojans", "UALR", 144),
    ("Arkansas-Pine Bluff Golden Lions", "UAPB", 14),
    ("Army Knights", "ARMY", 15),
    ("Auburn Tigers", "AUB", 16),
    ("Austin Peay Governors", "APSU", 17),
    ("BYU Cougars", "BYU", 18),
    ("Ball State Cardinals", "BALL", 19),
    ("Baylor Bears", "BAY", 20),
    ("Bellarmine Knights", "BELL", 21),
    ("Belmont Bruins", "BELM", 22),
    ("Bethune-Cookman Wildcats", "BCU", 23),
    ("Binghamton Bearcats", "BING", 24),
    ("Boise State Broncos", "BSU", 25),
    ("Boston College Eagles", "BC", 26),
    ("Boston Univ. Terriers", "BU", 27),
    ("Bowling Green Falcons", "BGSU", 28),
    ("Bradley Braves", "BRAD", 29),
    ("Brown Bears", "BRWN", 30),
    ("Bryant Bulldogs", "BRY", 31),
    ("Bucknell Bison", "BUCK", 32),
    ("Buffalo Bulls", "BUFF", 33),
    ("Butler Bulldogs", "BUT", 34),
    ("CSU Bakersfield Roadrunners", "CSUB", 36),
    ("CSU Fullerton Titans", "CSUF", 37),
    ("CSU Northridge Matadors", "CSUN", 38),
    ("Cal Baptist Lancers", "CBU", 39),
    ("Cal Poly Mustangs", "CPOL", 35),
    ("California Golden Bears", "CAL", 40),
    ("Campbell Fighting Camels", "CAMP", 41),
    ("Canisius Golden Griffins", "CAN", 42),
    ("Central Arkansas Bears", "UCA", 43),
    ("Central Connecticut St Blue Devils", "CCSU", 44),
    ("Central Michigan Chippewas", "CMU", 45),
    ("Charleston Cougars", "COFC", 46),
    ("Charleston Southern Buccaneers", "CHSO", 47),
    ("Charlotte 49ers", "CLT", 48),
    ("Chattanooga Mocs", "CHAT", 49),
    ("Chicago St Cougars", "CHST", 50),
    ("Cincinnati Bearcats", "CIN", 51),
    ("Clemson Tigers", "CLEM", 52),
    ("Cleveland St Vikings", "CLEV", 53),
    ("Coastal Carolina Chanticleers", "CCU", 54),
    ("Colgate Raiders", "COLG", 55),
    ("Colorado Buffaloes", "COLO", 56),
    ("Colorado St Rams", "CSU", 57),
    ("Columbia Lions", "COLM", 58),
    ("Cornell Big Red", "COR", 60),
    ("Creighton Bluejays", "CREI", 61),
    ("Dartmouth Big Green", "DART", 62),
    ("Davidson Wildcats", "DAV", 63),
    ("Dayton Flyers", "DAY", 64),
    ("DePaul Blue Demons", "DEP", 65),
    ("Delaware Blue Hens", "DEL", 66),
    ("Delaware St Hornets", "DSU", 67),
    ("Denver Pioneers", "DEN", 68),
    ("Detroit Mercy Titans", "DET", 69),
    ("Drake Bulldogs", "DRKE", 70),
    ("Drexel Dragons", "DREX", 71),
    ("Duke Blue Devils", "DUKE", 72),
    ("Duquesne Dukes", "DUQ", 73),
    ("East Carolina Pirates", "ECU", 74),
    ("East Tennessee St Buccaneers", "ETSU", 75),
    ("East Texas A&M Lions", "ETAM", 76),
    ("Eastern Illinois Panthers", "EIU", 77),
    ("Eastern Kentucky Colonels", "EKU", 78),
    ("Eastern Michigan Eagles", "EMU", 79),
    ("Eastern Washington Eagles", "EWU", 80),
    ("Elon Phoenix", "ELON", 81),
    ("Evansville Purple Aces", "EVAN", 82),
    ("Fairfield Stags", "FAIR", 83),
    ("Fairleigh Dickinson Knights", "FDU", 84),
    ("Florida A&M Rattlers", "FAMU", 85),
    ("Florida Atlantic Owls", "FAU", 86),
    ("Florida Gators", "FLA", 87),
    ("Florida Gulf Coast Eagles", "FGCU", 88),
    ("Florida Int'l Golden Panthers", "FIU", 89),
    ("Florida St Seminoles", "FSU", 90),
    ("Fordham Rams", "FORD", 91),
    ("Fort Wayne Mastodons", "PFW", 237),
    ("Fresno St Bulldogs", "FRES", 92),
    ("Furman Paladins", "FUR", 93),
    ("GW Revolutionaries", "GW", 96),
    ("Gardner-Webb Bulldogs", "GWEB", 94),
    ("George Mason Patriots", "GMU", 95),
    ("Georgetown Hoyas", "GTWN", 97),
    ("Georgia Bulldogs", "UGA", 98),
    ("Georgia Southern Eagles", "GASO", 99),
    ("Georgia St Panthers", "GAST", 100),
    ("Georgia Tech Yellow Jackets", "GT", 101),
    ("Gonzaga Bulldogs", "GONZ", 102),
    ("Grand Canyon Antelopes", "GCU", 104),
    ("Green Bay Phoenix", "GB", 105),
    ("Hampton Pirates", "HAMP", 106),
    ("Harvard Crimson", "HARV", 107),
    ("Hawai'i Rainbow Warriors", "HAW", 108),
    ("High Point Panthers", "HPU", 109),
    ("Hofstra Pride", "HOF", 110),
    ("Holy Cross Crusaders", "HC", 111),
    ("Houston Christian Huskies", "HCU", 112),
    ("Houston Cougars", "HOU", 113),
    ("IUPUI Jaguars", "IUPU", 115),
    ("Idaho State Bengals", "IDST", 116),
    ("Idaho Vandals", "IDHO", 117),
    ("Illinois Fighting Illini", "ILL", 118),
    ("Illinois St Redbirds", "ILST", 119),
    ("Incarnate Word Cardinals", "UIW", 120),
    ("Indiana Hoosiers", "IND", 121),
    ("Indiana St Sycamores", "INST", 122),
    ("Iona Gaels", "IONA", 123),
    ("Iowa Hawkeyes", "IOWA", 124),
    ("Iowa State Cyclones", "ISU", 125),
    ("Jackson St Tigers", "JKST", 126),
    ("Jacksonville Dolphins", "JAX", 127),
    ("Jacksonville St Gamecocks", "JVST", 128),
    ("James Madison Dukes", "JMU", 129),
    ("Kansas Jayhawks", "KU", 131),
    ("Kansas St Wildcats", "KSU", 132),
    ("Kennesaw St Owls", "KENN", 133),
    ("Kent State Golden Flashes", "KENT", 134),
    ("Kentucky Wildcats", "UK", 135),
    ("LIU Sharks", "LIU", 146),
    ("LSU Tigers", "LSU", 136),
    ("La Salle Explorers", "LAS", 137),
    ("Lafayette Leopards", "LAF", 138),
    ("Lamar Cardinals", "LAM", 139),
    ("Le Moyne Dolphins", "LEM", 140),
    ("Lehigh Mountain Hawks", "LEH", 141),
    ("Liberty Flames", "LIB", 142),
    ("Lindenwood Lions", "LIND", 366),
    ("Lipscomb Bisons", "LIP", 143),
    ("Long Beach St 49ers", "LBSU", 145),
    ("Longwood Lancers", "LONG", 147),
    ("Louisiana Ragin' Cajuns", "ULL", 148),
    ("Louisiana Tech Bulldogs", "LT", 149),
    ("Louisville Cardinals", "LOU", 150),
    ("Loyola (Chi) Ramblers", "LOYC", 151),
    ("Loyola (MD) Greyhounds", "LOYM", 152),
    ("Loyola Marymount Lions", "LMU", 153),
    ("Maine Black Bears", "ME", 154),
    ("Manhattan Jaspers", "MANH", 155),
    ("Marist Red Foxes", "MRST", 156),
    ("Marquette Golden Eagles", "MARQ", 157),
    ("Marshall Thundering Herd", "MRSH", 158),
    ("Maryland Terrapins", "MD", 160),
    ("Massachusetts Minutemen", "MASS", 161),
    ("McNeese Cowboys", "MCN", 162),
    ("Memphis Tigers", "MEM", 163),
    ("Mercer Bears", "MER", 164),
    ("Mercyhurst Lakers", "MERC", 165),
    ("Merrimack Warriors", "MERR", 166),
    ("Miami (OH) RedHawks", "MIOH", 167),
    ("Miami Hurricanes", "MIA", 168),
    ("Michigan St Spartans", "MSU", 169),
    ("Michigan Wolverines", "MICH", 170),
    ("Middle Tennessee Blue Raiders", "MTSU", 171),
    ("Milwaukee Panthers", "MKE", 172),
    ("Minnesota Golden Gophers", "MINN", 173),
    ("Miss Valley St Delta Devils", "MVSU", 175),
    ("Mississippi St Bulldogs", "MSST", 174),
    ("Missouri St Bears", "MOST", 176),
    ("Missouri Tigers", "MIZ", 177),
    ("Monmouth Hawks", "MON", 178),
    ("Montana Grizzlies", "MONT", 179),
    ("Montana St Bobcats", "MTST", 180),
    ("Morehead St Eagles", "MORE", 181),
    ("Morgan St Bears", "MORG", 182),
    ("Mt. St. Mary's Mountaineers", "MSM", 183),
    ("Murray St Racers", "MURR", 184),
    ("N Colorado Bears", "UNCO", 207),
    ("NC State Wolfpack", "NCST", 185),
    ("NJIT Highlanders", "NJIT", 186),
    ("Navy Midshipmen", "NAVY", 187),
    ("Nebraska Cornhuskers", "NEB", 188),
    ("Nevada Wolf Pack", "NEV", 189),
    ("New Hampshire Wildcats", "UNH", 190),
    ("New Haven Chargers", "NEWH", 1507),
    ("New Mexico Lobos", "UNM", 191),
    ("New Mexico St Aggies", "NMSU", 192),
    ("New Orleans Privateers", "UNO", 193),
    ("Niagara Purple Eagles", "NIAG", 194),
    ("Nicholls St Colonels", "NICH", 195),
    ("Norfolk St Spartans", "NORF", 196),
    ("North Alabama Lions", "UNA", 197),
    ("North Carolina A&T Aggies", "NCAT", 198),
    ("North Carolina Tar Heels", "UNC", 200),
    ("North Dakota Fighting Hawks", "UND", 201),
    ("North Dakota St Bison", "NDSU", 202),
    ("North Florida Ospreys", "UNF", 203),
    ("North Texas Mean Green", "UNT", 204),
    ("Northeastern Huskies", "NEU", 205),
    ("Northern Arizona Lumberjacks", "NAU", 206),
    ("Northern Illinois Huskies", "NIU", 208),
    ("Northern Iowa Panthers", "UNI", 209),
    ("Northern Kentucky Norse", "NKU", 210),
    ("Northwestern St Demons", "NWST", 211),
    ("Northwestern Wildcats", "NW", 212),
    ("Notre Dame Fighting Irish", "ND", 213),
    ("Oakland Golden Grizzlies", "OAK", 214),
    ("Ohio Bobcats", "OHIO", 215),
    ("Ohio State Buckeyes", "OSU", 216),
    ("Oklahoma Sooners", "OU", 217),
    ("Oklahoma St Cowboys", "OKST", 218),
    ("Old Dominion Monarchs", "ODU", 219),
    ("Ole Miss Rebels", "MISS", 220),
    ("Omaha Mavericks", "OMA", 221),
    ("Oral Roberts Golden Eagles", "ORU", 222),
    ("Oregon Ducks", "ORE", 223),
    ("Oregon St Beavers", "ORST", 224),
    ("Pacific Tigers", "PAC", 225),
    ("Penn State Nittany Lions", "PSU", 226),
    ("Pennsylvania Quakers", "PENN", 227),
    ("Pepperdine Waves", "PEPP", 228),
    ("Pittsburgh Panthers", "PITT", 229),
    ("Portland Pilots", "PORT", 230),
    ("Portland St Vikings", "PRST", 231),
    ("Prairie View Panthers", "PVAM", 232),
    ("Presbyterian Blue Hose", "PRES", 233),
    ("Princeton Tigers", "PRIN", 234),
    ("Providence Friars", "PROV", 235),
    ("Purdue Boilermakers", "PUR", 236),
    ("Queens University Royals", "QU", 362),
    ("Quinnipiac Bobcats", "QUIN", 238),
    ("Radford Highlanders", "RAD", 239),
    ("Rhode Island Rams", "URI", 240),
    ("Rice Owls", "RICE", 241),
    ("Richmond Spiders", "RICH", 242),
    ("Rider Broncs", "RID", 243),
    ("Robert Morris Colonials", "RMU", 244),
    ("Rutgers Scarlet Knights", "RUT", 245),
    ("SE Louisiana Lions", "SELA", 246),
    ("SE Missouri St Redhawks", "SEMO", 272),
    ("SIU-Edwardsville Cougars", "SIUE", 247),
    ("SMU Mustangs", "SMU", 248),
    ("Sacramento St Hornets", "SAC", 249),
    ("Sacred Heart Pioneers", "SHU", 250),
    ("Saint Joseph's Hawks", "SJU", 251),
    ("Saint Louis Billikens", "SLU", 252),
    ("Saint Mary's Gaels", "SMC", 253),
    ("Saint Peter's Peacocks", "SPU", 254),
    ("Sam Houston St Bearkats", "SHSU", 255),
    ("Samford Bulldogs", "SAMF", 256),
    ("San Diego St Aztecs", "SDSU", 257),
    ("San Diego Toreros", "USD", 258),
    ("San Francisco Dons", "SF", 259),
    ("San Jos\u00e9 St Spartans", "SJSU", 260),
    ("Santa Clara Broncos", "SCU", 261),
    ("Seattle Redhawks", "SEA", 262),
    ("Seton Hall Pirates", "HALL", 263),
    ("Siena Saints", "SIEN", 264),
    ("South Alabama Jaguars", "USA", 265),
    ("South Carolina Gamecocks", "SC", 266),
    ("South Carolina St Bulldogs", "SCST", 267),
    ("South Carolina Upstate Spartans", "UPST", 268),
    ("South Dakota Coyotes", "SDAK", 269),
    ("South Dakota St Jackrabbits", "SDST", 270),
    ("South Florida Bulls", "USF", 271),
    ("Southern Illinois Salukis", "SIU", 273),
    ("Southern Indiana Screaming Eagles", "USI", 365),
    ("Southern Jaguars", "SOU", 274),
    ("Southern Miss Golden Eagles", "SMIS", 275),
    ("Southern Utah Thunderbirds", "SUU", 276),
    ("St. Bonaventure Bonnies", "SBU", 277),
    ("St. Francis (PA) Red Flash", "SFPA", 278),
    ("St. John's Red Storm", "SJN", 279),
    ("St. Thomas (MN) Tommies", "STMN", 280),
    ("Stanford Cardinal", "STAN", 281),
    ("Stephen F. Austin Lumberjacks", "SFA", 282),
    ("Stetson Hatters", "STET", 283),
    ("Stonehill Skyhawks", "STNH", 284),
    ("Stony Brook Seawolves", "STON", 285),
    ("Syracuse Orange", "SYR", 286),
    ("TCU Horned Frogs", "TCU", 287),
    ("Tarleton State Texans", "TARL", 288),
    ("Temple Owls", "TEM", 289),
    ("Tenn-Martin Skyhawks", "UTM", 325),
    ("Tennessee St Tigers", "TNST", 290),
    ("Tennessee Tech Golden Eagles", "TNTH", 291),
    ("Tennessee Volunteers", "TENN", 292),
    ("Texas A&M Aggies", "TAMU", 293),
    ("Texas A&M-CC Islanders", "TAMC", 294),
    ("Texas Longhorns", "TEX", 295),
    ("Texas State Bobcats", "TXST", 297),
    ("Texas Tech Red Raiders", "TTU", 298),
    ("The Citadel Bulldogs", "CIT", 299),
    ("Toledo Rockets", "TOL", 300),
    ("Towson Tigers", "TOW", 301),
    ("Troy Trojans", "TROY", 302),
    ("Tulane Green Wave", "TUL", 303),
    ("Tulsa Golden Hurricane", "TLSA", 304),
    ("UAB Blazers", "UAB", 305),
    ("UC Davis Aggies", "UCD", 307),
    ("UC Irvine Anteaters", "UCI", 308),
    ("UC Riverside Highlanders", "UCR", 309),
    ("UC San Diego Tritons", "UCSD", 310),
    ("UC Santa Barbara Gauchos", "UCSB", 311),
    ("UCF Knights", "UCF", 312),
    ("UCLA Bruins", "UCLA", 313),
    ("UConn Huskies", "CONN", 314),
    ("UIC Flames", "UIC", 315),
    ("UL Monroe Warhawks", "ULM", 316),
    ("UMBC Retrievers", "UMBC", 317),
    ("UMKC Kangaroos", "UMKC", 130),
    ("UMass Lowell River Hawks", "UMAL", 318),
    ("UNC Asheville Bulldogs", "UNCA", 319),
    ("UNC Greensboro Spartans", "UNCG", 320),
    ("UNC Wilmington Seahawks", "UNCW", 321),
    ("UNLV Rebels", "UNLV", 322),
    ("USC Trojans", "USC", 323),
    ("UT Rio Grande Valley Vaqueros", "UTRGV", 326),
    ("UT-Arlington Mavericks", "UTA", 324),
    ("UTEP Miners", "UTEP", 327),
    ("UTSA Roadrunners", "UTSA", 328),
    ("Utah State Aggies", "USU", 329),
    ("Utah Tech Trailblazers", "UTEC", 330),
    ("Utah Utes", "UTAH", 331),
    ("Utah Valley Wolverines", "UVU", 332),
    ("VCU Rams", "VCU", 333),
    ("VMI Keydets", "VMI", 334),
    ("Valparaiso Beacons", "VALP", 335),
    ("Vanderbilt Commodores", "VAN", 336),
    ("Vermont Catamounts", "UVM", 337),
    ("Villanova Wildcats", "NOVA", 338),
    ("Virginia Cavaliers", "UVA", 339),
    ("Virginia Tech Hokies", "VT", 340),
    ("Wagner Seahawks", "WAG", 341),
    ("Wake Forest Demon Deacons", "WAKE", 342),
    ("Washington Huskies", "WASH", 343),
    ("Washington St Cougars", "WSU", 344),
    ("Weber State Wildcats", "WEB", 345),
    ("West Georgia Wolves", "WGA", 346),
    ("West Virginia Mountaineers", "WVU", 347),
    ("Western Carolina Catamounts", "WCU", 348),
    ("Western Illinois Leathernecks", "WIU", 349),
    ("Western Kentucky Hilltoppers", "WKU", 350),
    ("Western Michigan Broncos", "WMU", 351),
    ("Wichita St Shockers", "WICH", 352),
    ("William & Mary Tribe", "WM", 353),
    ("Winthrop Eagles", "WIN", 354),
    ("Wisconsin Badgers", "WIS", 355),
    ("Wofford Terriers", "WOF", 356),
    ("Wright St Raiders", "WRST", 357),
    ("Wyoming Cowboys", "WYO", 358),
    ("Xavier Musketeers", "XAV", 359),
    ("Yale Bulldogs", "YALE", 360),
    ("Youngstown St Penguins", "YSU", 361),
]


def _derive_short_name(full_name: str) -> str:
    """Strip the last word (mascot) from a team name to get the short name."""
    parts = full_name.rsplit(" ", 1)
    return parts[0] if len(parts) > 1 else full_name


def upgrade() -> None:
    """Fix NCAAB team abbreviations and short_names."""
    conn = op.get_bind()

    result = conn.execute(text("SELECT id FROM sports_leagues WHERE code = 'NCAAB'"))
    row = result.fetchone()
    if not row:
        print("NCAAB league not found - skipping")
        return
    league_id = row[0]

    update_sql = text("""
        UPDATE sports_teams
        SET abbreviation = :abbr,
            short_name = :short_name
        WHERE league_id = :lid
          AND (external_codes->>'cbb_team_id')::int = :cbb_id
    """)

    updated = 0
    missed = 0
    for name, abbr, cbb_id in _NCAAB_TEAMS:
        short_name = _derive_short_name(name)
        result = conn.execute(update_sql, {
            "abbr": abbr,
            "short_name": short_name,
            "lid": league_id,
            "cbb_id": cbb_id,
        })
        if result.rowcount > 0:
            updated += 1
        else:
            missed += 1
            print(f"  MISS: cbb_id={cbb_id} name='{name}' — not found in DB")

    print(f"Updated {updated} NCAAB team abbreviations ({missed} not matched)")


def downgrade() -> None:
    """Revert to old derived abbreviations is not practical.

    The old abbreviations were garbage (collisions, unrecognizable). There is no
    meaningful downgrade — the data was broken before. This is a no-op downgrade.
    """
    pass
