"""Add team color columns and seed with color data from GameTheme.swift.

Adds color_light_hex and color_dark_hex VARCHAR(7) columns to sports_teams
and populates them for 408 teams across NBA, NHL, and NCAAB.

Revision ID: 20260211_000002
Revises: 20260211_000001
Create Date: 2026-02-11
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

revision = "20260211_000002"
down_revision = "20260211_000001"
branch_labels = None
depends_on = None

_TEAM_COLORS: dict[str, dict[str, str]] = {
    'Atlanta Hawks': {"light": '#E14434', "dark": '#C4D600', "league": 'NBA'},
    'Boston Celtics': {"light": '#007A33', "dark": '#009B3A', "league": 'NBA'},
    'Brooklyn Nets': {"light": '#000000', "dark": '#646464', "league": 'NBA'},
    'Charlotte Hornets': {"light": '#1D1160', "dark": '#00788C', "league": 'NBA'},
    'Chicago Bulls': {"light": '#CE1141', "dark": '#CE1141', "league": 'NBA'},
    'Cleveland Cavaliers': {"light": '#860038', "dark": '#FDBB30', "league": 'NBA'},
    'Dallas Mavericks': {"light": '#0053BC', "dark": '#002B5C', "league": 'NBA'},
    'Denver Nuggets': {"light": '#0D2240', "dark": '#FFC627', "league": 'NBA'},
    'Detroit Pistons': {"light": '#C8102E', "dark": '#1D428A', "league": 'NBA'},
    'Golden State Warriors': {"light": '#1D428A', "dark": '#FFC72C', "league": 'NBA'},
    'Houston Rockets': {"light": '#CE1141', "dark": '#C4CED3', "league": 'NBA'},
    'Indiana Pacers': {"light": '#002D62', "dark": '#FDBB30', "league": 'NBA'},
    'LA Clippers': {"light": '#C8102E', "dark": '#1D4294', "league": 'NBA'},
    'LA Lakers': {"light": '#552582', "dark": '#FDB927', "league": 'NBA'},
    'Los Angeles Clippers': {"light": '#C8102E', "dark": '#1D4294', "league": 'NBA'},
    'Los Angeles Lakers': {"light": '#552582', "dark": '#FDB927', "league": 'NBA'},
    'Memphis Grizzlies': {"light": '#5D76A9', "dark": '#12173F', "league": 'NBA'},
    'Miami Heat': {"light": '#98002E', "dark": '#F9A01B', "league": 'NBA'},
    'Milwaukee Bucks': {"light": '#00471B', "dark": '#F0EBD2', "league": 'NBA'},
    'Minnesota Timberwolves': {"light": '#0C2340', "dark": '#236192', "league": 'NBA'},
    'New Orleans Pelicans': {"light": '#001641', "dark": '#E13A3E', "league": 'NBA'},
    'New York Knicks': {"light": '#006BB6', "dark": '#F58426', "league": 'NBA'},
    'Oklahoma City Thunder': {"light": '#007DC3', "dark": '#EF3B24', "league": 'NBA'},
    'Orlando Magic': {"light": '#007DC5', "dark": '#C4CED3', "league": 'NBA'},
    'Philadelphia 76ers': {"light": '#006BB6', "dark": '#ED174C', "league": 'NBA'},
    'Phoenix Suns': {"light": '#1D1160', "dark": '#E55F20', "league": 'NBA'},
    'Portland Trail Blazers': {"light": '#E03A3E', "dark": '#63666A', "league": 'NBA'},
    'Sacramento Kings': {"light": '#5B2B82', "dark": '#63717A', "league": 'NBA'},
    'San Antonio Spurs': {"light": '#C4CED3', "dark": '#061922', "league": 'NBA'},
    'Toronto Raptors': {"light": '#CE1141', "dark": '#CE1141', "league": 'NBA'},
    'Utah Jazz': {"light": '#002B5C', "dark": '#F9A01B', "league": 'NBA'},
    'Washington Wizards': {"light": '#002B5C', "dark": '#E31837', "league": 'NBA'},
    'Abilene Christian': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Air Force': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Akron': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Alabama': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Alabama A&M': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Alabama State': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Albany': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Alcorn State': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'American': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Appalachian State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Arizona': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Arizona State': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Arkansas': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Arkansas State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Army': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Auburn': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Austin Peay': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'BYU': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Ball State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Baylor': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Bellarmine': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Belmont': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Bethune Cookman': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Binghamton': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Boise State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Boston College': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Boston University': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Bowling Green': {"light": '#78461E', "dark": '#BE8C5A', "league": 'NCAAB'},
    'Bradley': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Brown': {"light": '#78461E', "dark": '#BE8C5A', "league": 'NCAAB'},
    'Bryant': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Bucknell': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Buffalo': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Butler': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Cal Poly': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Cal State Bakersfield': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Cal State Fullerton': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Cal State Northridge': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'California': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'California Baptist': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Campbell': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Canisius': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Central Arkansas': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Central Connecticut': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Central Florida': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Central Michigan': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Charleston': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Charleston Southern': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Charlotte': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Chattanooga': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Chicago State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Cincinnati': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Clemson': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Cleveland State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Coastal Carolina': {"light": '#008080', "dark": '#50D2C8', "league": 'NCAAB'},
    'Colgate': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Colorado': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Colorado State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Columbia': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Connecticut': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Coppin State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Cornell': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Creighton': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Dartmouth': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Davidson': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Dayton': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'DePaul': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Delaware': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Delaware State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Denver': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Detroit Mercy': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Drake': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Drexel': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Duke': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Duquesne': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'East Carolina': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'East Tennessee State': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'East Texas A&M': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Eastern Illinois': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Eastern Kentucky': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Eastern Michigan': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Eastern Washington': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Elon': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Evansville': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Fairfield': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Fairleigh Dickinson': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Florida': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Florida A&M': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Florida Atlantic': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Florida Gulf Coast': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Florida International': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Florida State': {"light": '#82001E', "dark": '#E65A64', "league": 'NCAAB'},
    'Fordham': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Fort Wayne': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Fresno State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Furman': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'GW': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Gardner-Webb': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'George Mason': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'George Washington': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Georgetown': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Georgia': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Georgia Southern': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Georgia State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Georgia Tech': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Gonzaga': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Grand Canyon': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Green Bay': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Hampton': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Harvard': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    "Hawai'i": {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'High Point': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Hofstra': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Holy Cross': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Houston': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Houston Christian': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'IUPUI': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Idaho': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Idaho State': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Illinois': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Illinois State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Incarnate Word': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Indiana': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Indiana State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Iona': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Iowa': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Iowa State': {"light": '#96001E', "dark": '#F06464', "league": 'NCAAB'},
    'Jackson State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Jacksonville': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Jacksonville State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'James Madison': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Kansas': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Kansas State': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Kennesaw State': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Kent State': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Kentucky': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'LIU': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'LSU': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'La Salle': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Lafayette': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Lamar': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Le Moyne': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Lehigh': {"light": '#78461E', "dark": '#BE8C5A', "league": 'NCAAB'},
    'Liberty': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Lindenwood': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Lipscomb': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Little Rock': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Long Beach State': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Longwood': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Louisiana': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Louisiana Monroe': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Louisiana Tech': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Louisville': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Loyola Chicago': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Loyola Maryland': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Loyola Marymount': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Maine': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Manhattan': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Marist': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Marquette': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Marshall': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Maryland': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Massachusetts': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'McNeese': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Memphis': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Mercer': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Mercyhurst': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Merrimack': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Miami': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Miami (OH)': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Michigan': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Michigan State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Middle Tennessee': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Milwaukee': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Minnesota': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Miss Valley St': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Mississippi': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Mississippi State': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Missouri': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Missouri State': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Monmouth': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Montana': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Montana State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Morehead State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Morgan State': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    "Mount St Mary's": {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Murray State': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'N Colorado': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'NC State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'NJIT': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Navy': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Nebraska': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Nevada': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'New Hampshire': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'New Haven': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'New Mexico': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'New Mexico State': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'New Orleans': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Niagara': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Nicholls': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Norfolk State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'North Alabama': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'North Carolina': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'North Carolina A&T': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'North Dakota': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'North Dakota State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'North Florida': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'North Texas': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Northeastern': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Northern Arizona': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Northern Illinois': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Northern Iowa': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Northern Kentucky': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Northwestern': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Northwestern State': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Notre Dame': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Oakland': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Ohio': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Ohio State': {"light": '#BB0000', "dark": '#F06464', "league": 'NCAAB'},
    'Oklahoma': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Oklahoma State': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Old Dominion': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Ole Miss': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Omaha': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Oral Roberts': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Oregon': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Oregon State': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Pacific': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Penn': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Penn State': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Pepperdine': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Pittsburgh': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Portland': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Portland State': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Prairie View': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Presbyterian': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Princeton': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Providence': {"light": '#808080', "dark": '#AAAAAA', "league": 'NCAAB'},
    'Purdue': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Queens University': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Quinnipiac': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Radford': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Rhode Island': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Rice': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Richmond': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Rider': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Robert Morris': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Rutgers': {"light": '#BB0000', "dark": '#F06464', "league": 'NCAAB'},
    'SE Louisiana': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'SE Missouri St': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'SIU-Edwardsville': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'SMU': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Sacramento St': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Sacred Heart': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    "Saint Joseph's": {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Saint Louis': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    "Saint Mary's": {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    "Saint Peter's": {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Sam Houston': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Samford': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'San Diego': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'San Diego State': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'San Francisco': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'San Jos\u00e9 St': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Santa Clara': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Seattle': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Seton Hall': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Siena': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'South Alabama': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'South Carolina': {"light": '#82001E', "dark": '#E65A64', "league": 'NCAAB'},
    'South Carolina State': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'South Carolina Upstate': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'South Dakota': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'South Dakota State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'South Florida': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Southern': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Southern Illinois': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Southern Indiana': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Southern Miss': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Southern Utah': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'St. Bonaventure': {"light": '#78461E', "dark": '#BE8C5A', "league": 'NCAAB'},
    'St. Francis': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    "St. John's": {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'St. Thomas': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Stanford': {"light": '#96001E', "dark": '#F06464', "league": 'NCAAB'},
    'Stephen F. Austin': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Stetson': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Stonehill': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Stony Brook': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Syracuse': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'TCU': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Tarleton State': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Temple': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Tennessee': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Tennessee State': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Tennessee Tech': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Texas': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Texas A&M': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Texas A&M-CC': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Texas State': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Texas Tech': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'The Citadel': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Toledo': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Towson': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Troy': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Tulane': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Tulsa': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UAB': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'UC Davis': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'UC Irvine': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UC Riverside': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UC San Diego': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'UC Santa Barbara': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UCF': {"light": '#1E1E1E', "dark": '#AAAAAA', "league": 'NCAAB'},
    'UCLA': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UConn': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'UIC': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UL Monroe': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'UMBC': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'UMKC': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UMass Lowell': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UNC Asheville': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UNC Greensboro': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'UNC Wilmington': {"light": '#008080', "dark": '#50D2C8', "league": 'NCAAB'},
    'UNLV': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'USC': {"light": '#96001E', "dark": '#F06464', "league": 'NCAAB'},
    'UT Rio Grande Valley': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'UT-Arlington': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'UTEP': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'UTSA': {"light": '#E67800', "dark": '#FFAA46', "league": 'NCAAB'},
    'Utah': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Utah State': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Utah Tech': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Utah Valley': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'VCU': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'VMI': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Valparaiso': {"light": '#78461E', "dark": '#BE8C5A', "league": 'NCAAB'},
    'Vanderbilt': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Vermont': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Villanova': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Virginia': {"light": '#00205B', "dark": '#6496DC', "league": 'NCAAB'},
    'Virginia Tech': {"light": '#64141E', "dark": '#C8646E', "league": 'NCAAB'},
    'Wagner': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Wake Forest': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Washington': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Washington State': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Weber State': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'West Georgia': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'West Virginia': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Western Carolina': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Western Illinois': {"light": '#6428A0', "dark": '#AA82FF', "league": 'NCAAB'},
    'Western Kentucky': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Western Michigan': {"light": '#78461E', "dark": '#BE8C5A', "league": 'NCAAB'},
    'Wichita St': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'William & Mary': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Winthrop': {"light": '#A50016', "dark": '#E65A64', "league": 'NCAAB'},
    'Wisconsin': {"light": '#96001E', "dark": '#F06464', "league": 'NCAAB'},
    'Wofford': {"light": '#B99B0F', "dark": '#FFD250', "league": 'NCAAB'},
    'Wright St': {"light": '#007832', "dark": '#50C878', "league": 'NCAAB'},
    'Wyoming': {"light": '#78461E', "dark": '#BE8C5A', "league": 'NCAAB'},
    'Xavier': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Yale': {"light": '#0064C8', "dark": '#50A0FF', "league": 'NCAAB'},
    'Youngstown St': {"light": '#C8102E', "dark": '#F06464', "league": 'NCAAB'},
    'Anaheim Ducks': {"light": '#FC4C02', "dark": '#000000', "league": 'NHL'},
    'Arizona Coyotes': {"light": '#8C2633', "dark": '#E2D6B5', "league": 'NHL'},
    'Boston Bruins': {"light": '#000000', "dark": '#FCB514', "league": 'NHL'},
    'Buffalo Sabres': {"light": '#002654', "dark": '#FCB514', "league": 'NHL'},
    'Calgary Flames': {"light": '#C8102E', "dark": '#F1BE48', "league": 'NHL'},
    'Carolina Hurricanes': {"light": '#CE1126', "dark": '#A2AAAD', "league": 'NHL'},
    'Chicago Blackhawks': {"light": '#CF0A2C', "dark": '#000000', "league": 'NHL'},
    'Colorado Avalanche': {"light": '#6F263D', "dark": '#236192', "league": 'NHL'},
    'Columbus Blue Jackets': {"light": '#002654', "dark": '#CE1126', "league": 'NHL'},
    'Dallas Stars': {"light": '#006847', "dark": '#8F8F8C', "league": 'NHL'},
    'Detroit Red Wings': {"light": '#CE1126', "dark": '#FFFFFF', "league": 'NHL'},
    'Edmonton Oilers': {"light": '#041E42', "dark": '#FC4C02', "league": 'NHL'},
    'Florida Panthers': {"light": '#041E42', "dark": '#C8102E', "league": 'NHL'},
    'Los Angeles Kings': {"light": '#111111', "dark": '#A2AAAD', "league": 'NHL'},
    'Minnesota Wild': {"light": '#154734', "dark": '#AF2324', "league": 'NHL'},
    'Montreal Canadiens': {"light": '#AF1E2D', "dark": '#192168', "league": 'NHL'},
    'Nashville Predators': {"light": '#FFB81C', "dark": '#041E42', "league": 'NHL'},
    'New Jersey Devils': {"light": '#000000', "dark": '#CE1126', "league": 'NHL'},
    'New York Islanders': {"light": '#00539B', "dark": '#F47D30', "league": 'NHL'},
    'New York Rangers': {"light": '#0038A8', "dark": '#CE1126', "league": 'NHL'},
    'Ottawa Senators': {"light": '#000000', "dark": '#C8102E', "league": 'NHL'},
    'Philadelphia Flyers': {"light": '#F74902', "dark": '#000000', "league": 'NHL'},
    'Pittsburgh Penguins': {"light": '#000000', "dark": '#FCB514', "league": 'NHL'},
    'San Jose Sharks': {"light": '#006D75', "dark": '#EA7200', "league": 'NHL'},
    'Seattle Kraken': {"light": '#001628', "dark": '#99D9D9', "league": 'NHL'},
    'St. Louis Blues': {"light": '#002F87', "dark": '#FCB514', "league": 'NHL'},
    'Tampa Bay Lightning': {"light": '#002868', "dark": '#FFFFFF', "league": 'NHL'},
    'Toronto Maple Leafs': {"light": '#00205B', "dark": '#FFFFFF', "league": 'NHL'},
    'Vancouver Canucks': {"light": '#00205B', "dark": '#0A863D', "league": 'NHL'},
    'Vegas Golden Knights': {"light": '#333F42', "dark": '#B9975B', "league": 'NHL'},
    'Washington Capitals': {"light": '#C8102E', "dark": '#041E42', "league": 'NHL'},
    'Winnipeg Jets': {"light": '#041E42', "dark": '#004C97', "league": 'NHL'},
}


def upgrade() -> None:
    """Add color columns and populate with team color data."""
    # 1. Add columns
    op.add_column(
        "sports_teams",
        sa.Column("color_light_hex", sa.String(7), nullable=True),
    )
    op.add_column(
        "sports_teams",
        sa.Column("color_dark_hex", sa.String(7), nullable=True),
    )

    # 2. Populate from color data
    conn = op.get_bind()

    # Get league IDs
    leagues = {}
    for row in conn.execute(text("SELECT id, code FROM sports_leagues")):
        leagues[row[1]] = row[0]

    # NBA/NHL: match by league_code + exact name
    nba_nhl_update = text("""
        UPDATE sports_teams
        SET color_light_hex = :light, color_dark_hex = :dark
        WHERE league_id = :lid AND name = :name
    """)

    # NCAAB: match by league_code + name prefix (LIKE)
    ncaab_update = text("""
        UPDATE sports_teams
        SET color_light_hex = :light, color_dark_hex = :dark
        WHERE league_id = :lid AND name LIKE :pattern
          AND color_light_hex IS NULL
    """)

    updated = 0
    missed = 0

    # Sort NCAAB keys by length DESC so longest prefixes match first
    # (e.g., "Alabama A&M" before "Alabama")
    sorted_keys = sorted(
        _TEAM_COLORS.keys(),
        key=lambda k: (_TEAM_COLORS[k]["league"] != "NCAAB", -len(k)),
    )

    for name in sorted_keys:
        data = _TEAM_COLORS[name]
        league_code = data["league"]
        league_id = leagues.get(league_code)

        if not league_id:
            print(f"  SKIP: league {league_code} not found for {name}")
            missed += 1
            continue

        if league_code in ("NBA", "NHL"):
            result = conn.execute(nba_nhl_update, {
                "light": data["light"],
                "dark": data["dark"],
                "lid": league_id,
                "name": name,
            })
            if result.rowcount > 0:
                updated += result.rowcount
            else:
                missed += 1
                print(f"  MISS: {league_code} exact name='{name}' — not found in DB")
        else:
            # NCAAB prefix match — only update rows that don't already have colors
            # (prevents shorter prefix from overwriting longer match)
            pattern = f"{name}%"
            result = conn.execute(ncaab_update, {
                "light": data["light"],
                "dark": data["dark"],
                "lid": league_id,
                "pattern": pattern,
            })
            if result.rowcount > 0:
                updated += result.rowcount
            else:
                missed += 1
                print(f"  MISS: NCAAB prefix='{name}%' — no uncolored match in DB")

    print(f"Updated {updated} team colors ({missed} keys not matched)")


def downgrade() -> None:
    """Remove color columns."""
    op.drop_column("sports_teams", "color_dark_hex")
    op.drop_column("sports_teams", "color_light_hex")
