/**
 * Guardrails & Invariant Enforcement (Frontend)
 *
 * CANONICAL SOURCE OF TRUTH: api/app/services/pipeline/stages/validate_blocks.py
 * (numeric constants from api/app/services/pipeline/stages/block_types.py)
 *
 * Every constant and enumeration in this file must mirror the backend Python files.
 * Do NOT change values here without updating the backend canonical source first.
 * CI enforces this contract via scripts/check_guardrails_sync.py — divergence
 * causes a failing check on every PR that touches either file.
 *
 * INVARIANTS (Non-negotiable)
 * ===========================
 * 1. Narrative blocks ≤ 7
 * 2. Embedded tweets ≤ 5
 * 3. Zero required social dependencies
 *
 * ENFORCEMENT RULES
 * =================
 * - Violations must be logged LOUDLY (console.error with context)
 * - Violations must be visible in dev builds
 * - NO silent truncation
 * - NO auto-correction without surfacing the issue
 *
 * If a future change violates any invariant, the change is INCORRECT.
 * These guardrails define the product.
 */

import type { FlowSource, NarrativeBlock, SemanticRole } from "./api/sportsAdmin/gameFlowTypes";

// =============================================================================
// INVARIANT CONSTANTS
// =============================================================================

/**
 * Required semantic role types that every flow must contain.
 * Mirrors REQUIRED_BLOCK_TYPES in api/app/services/pipeline/stages/validate_blocks.py.
 * Keep in sync: any change here must be reflected there and vice versa.
 */
export const REQUIRED_BLOCK_TYPE_ROLES: readonly SemanticRole[] = [
  "SETUP",
  "RESOLUTION",
] as const;

/** Maximum number of narrative blocks per game */
export const MAX_BLOCKS = 7;

/**
 * Minimum number of narrative blocks per game.
 * Floor is 3, not 4: blowout games produce fewer distinct narrative segments
 * (SETUP → DECISION_POINT → RESOLUTION) and 3 is a valid, complete arc.
 * Canonical value is shared with backend validate_blocks.py MIN_BLOCKS = 3.
 */
export const MIN_BLOCKS = 3;

/** Maximum embedded tweets per game */
export const MAX_EMBEDDED_TWEETS = 5;

/** Maximum tweets per block */
export const MAX_TWEETS_PER_BLOCK = 1;

/** Target read time bounds (seconds) */
export const MIN_READ_TIME_SECONDS = 20;
export const MAX_READ_TIME_SECONDS = 60;

/** Words per minute for read time calculation */
export const WORDS_PER_MINUTE = 250;

/**
 * Maximum total words across all blocks.
 * Matches MAX_TOTAL_WORDS = 600 in block_types.py.
 * The backend enforces this as a warning-level check; frontend mirrors it.
 * Value is intentionally higher than (MAX_READ_TIME_SECONDS/60)*WORDS_PER_MINUTE
 * to accommodate richer narratives (see block_types.py comment).
 */
export const MAX_TOTAL_WORDS = 600;

// =============================================================================
// FLOW SOURCE CONSTANTS
// =============================================================================

/**
 * Block content was generated by the LLM narrative pipeline (standard path).
 * Template-source flows should display identically; no UI differentiation required.
 */
export const FLOW_SOURCE_LLM: FlowSource = "LLM";

/**
 * Block content was produced by the deterministic template fallback.
 * Structurally valid; passes all guardrail checks.  No embedded tweets are
 * attached to template blocks (the tweet attachment runs after validation, but
 * templates produce zero-tweet blocks — the MAX_EMBEDDED_TWEETS invariant
 * is therefore trivially satisfied).
 */
export const FLOW_SOURCE_TEMPLATE: FlowSource = "TEMPLATE";

// =============================================================================
// VALIDATION TYPES
// =============================================================================

export type ViolationSeverity = "error" | "warning";

export interface GuardrailViolation {
  invariant: string;
  message: string;
  actualValue: unknown;
  limitValue: unknown;
  severity: ViolationSeverity;
}

export interface GuardrailResult {
  gameId: number | null;
  passed: boolean;
  violations: GuardrailViolation[];
  metrics: {
    blockCount: number;
    embeddedTweetCount: number;
    totalWords: number;
    hasSocialData: boolean;
    socialRequired: boolean;
  };
}

// =============================================================================
// PRE-RENDER VALIDATION
// =============================================================================

/**
 * Validate blocks before rendering.
 *
 * Call this in components before rendering block-based content.
 * Logs violations loudly in development.
 *
 * @param blocks - Blocks to validate
 * @param gameId - Game identifier for logging
 * @returns Validation result
 */
export function validateBlocksPreRender(
  blocks: NarrativeBlock[],
  gameId: number | null = null
): GuardrailResult {
  const violations: GuardrailViolation[] = [];

  // Count metrics
  const blockCount = blocks.length;
  const embeddedTweetCount = blocks.filter((b) => b.embeddedSocialPostId).length;
  const totalWords = blocks.reduce((sum, b) => {
    const words = (b.narrative || "").split(/\s+/).filter(Boolean).length;
    return sum + words;
  }, 0);

  // Check block count upper bound
  if (blockCount > MAX_BLOCKS) {
    violations.push({
      invariant: "MAX_BLOCKS",
      message: `Block count ${blockCount} exceeds maximum ${MAX_BLOCKS}`,
      actualValue: blockCount,
      limitValue: MAX_BLOCKS,
      severity: "error",
    });
  }

  // Check block count lower bound (warning)
  if (blockCount > 0 && blockCount < MIN_BLOCKS) {
    violations.push({
      invariant: "MIN_BLOCKS",
      message: `Block count ${blockCount} below minimum ${MIN_BLOCKS}`,
      actualValue: blockCount,
      limitValue: MIN_BLOCKS,
      severity: "warning",
    });
  }

  // Check embedded tweet count
  if (embeddedTweetCount > MAX_EMBEDDED_TWEETS) {
    violations.push({
      invariant: "MAX_EMBEDDED_TWEETS",
      message: `Embedded tweet count ${embeddedTweetCount} exceeds maximum ${MAX_EMBEDDED_TWEETS}`,
      actualValue: embeddedTweetCount,
      limitValue: MAX_EMBEDDED_TWEETS,
      severity: "error",
    });
  }

  // Check total word count (warning)
  if (totalWords > MAX_TOTAL_WORDS) {
    violations.push({
      invariant: "MAX_TOTAL_WORDS",
      message: `Total word count ${totalWords} may exceed ${MAX_READ_TIME_SECONDS}s read time`,
      actualValue: totalWords,
      limitValue: MAX_TOTAL_WORDS,
      severity: "warning",
    });
  }

  // Check required block types are present
  const presentRoles = new Set(blocks.map((b) => b.role));
  for (const requiredRole of REQUIRED_BLOCK_TYPE_ROLES) {
    if (!presentRoles.has(requiredRole)) {
      violations.push({
        invariant: "REQUIRED_BLOCK_TYPE",
        message: `Required block type ${requiredRole} is missing from flow`,
        actualValue: [...presentRoles],
        limitValue: requiredRole,
        severity: "error",
      });
    }
  }

  // Check RESOLUTION block for specificity warning (mirrors _check_resolution_specificity)
  // Soft check: warns when the backend flagged the block as lacking a traceable
  // final-window play reference. Does not affect the passed/error outcome.
  const resolutionBlock = blocks.find((b) => b.role === "RESOLUTION");
  if (resolutionBlock?.resolutionSpecificityWarning) {
    violations.push({
      invariant: "RESOLUTION_SPECIFICITY",
      message:
        "RESOLUTION block has no traceable reference to a final-window play — narrative may be generic",
      actualValue: resolutionBlock.blockIndex,
      limitValue: "at least one named play or score from the final game window",
      severity: "warning",
    });
  }

  // Check block structure
  blocks.forEach((block, i) => {
    // Required fields
    if (block.narrative === null || block.narrative === undefined) {
      violations.push({
        invariant: "BLOCK_STRUCTURE",
        message: `Block ${i} missing narrative`,
        actualValue: block.narrative,
        limitValue: "non-null string",
        severity: "error",
      });
    }

    if (!block.role) {
      violations.push({
        invariant: "BLOCK_STRUCTURE",
        message: `Block ${i} missing role`,
        actualValue: block.role,
        limitValue: "valid role",
        severity: "error",
      });
    }
  });

  const passed = !violations.some((v) => v.severity === "error");

  const result: GuardrailResult = {
    gameId,
    passed,
    violations,
    metrics: {
      blockCount,
      embeddedTweetCount,
      totalWords,
      hasSocialData: embeddedTweetCount > 0,
      socialRequired: false,
    },
  };

  // Log violations loudly
  logValidationResult(result, "pre_render");

  return result;
}

/**
 * Validate that removing social data doesn't change structure.
 *
 * @param blocksWithSocial - Blocks including embedded tweets
 * @param blocksWithoutSocial - Blocks without social (optional)
 * @param gameId - Game identifier
 * @returns Validation result
 */
export function validateSocialIndependence(
  blocksWithSocial: NarrativeBlock[],
  blocksWithoutSocial: NarrativeBlock[] | null,
  gameId: number | null = null
): GuardrailResult {
  const violations: GuardrailViolation[] = [];
  let socialRequired = false;

  if (blocksWithoutSocial !== null) {
    // Block count must match
    if (blocksWithSocial.length !== blocksWithoutSocial.length) {
      violations.push({
        invariant: "SOCIAL_INDEPENDENCE",
        message: `Block count differs with/without social: ${blocksWithSocial.length} vs ${blocksWithoutSocial.length}`,
        actualValue: blocksWithSocial.length,
        limitValue: blocksWithoutSocial.length,
        severity: "error",
      });
      socialRequired = true;
    }

    // Narratives must match
    blocksWithSocial.forEach((block, i) => {
      const other = blocksWithoutSocial[i];
      if (other && block.narrative !== other.narrative) {
        violations.push({
          invariant: "SOCIAL_INDEPENDENCE",
          message: `Block ${i} narrative differs with/without social`,
          actualValue: "with_social",
          limitValue: "without_social",
          severity: "error",
        });
        socialRequired = true;
      }
    });
  }

  const passed = !violations.some((v) => v.severity === "error");

  const result: GuardrailResult = {
    gameId,
    passed,
    violations,
    metrics: {
      blockCount: blocksWithSocial.length,
      embeddedTweetCount: blocksWithSocial.filter((b) => b.embeddedSocialPostId).length,
      totalWords: 0,
      hasSocialData: blocksWithSocial.some((b) => b.embeddedSocialPostId),
      socialRequired,
    },
  };

  logValidationResult(result, "social_independence");

  return result;
}

// =============================================================================
// LOGGING
// =============================================================================

/**
 * Log validation result with appropriate level.
 *
 * Violations are logged LOUDLY per guardrails contract.
 */
function logValidationResult(result: GuardrailResult, checkpoint: string): void {
  // Only log in development or when there are violations
  const isDev = process.env.NODE_ENV === "development";

  if (result.passed && result.violations.length === 0) {
    if (isDev) {
      console.log(
        `[GUARDRAIL] ✓ ${checkpoint} passed`,
        {
          gameId: result.gameId,
          ...result.metrics,
        }
      );
    }
    return;
  }

  // Log each violation
  result.violations.forEach((violation) => {
    const logFn = violation.severity === "error" ? console.error : console.warn;
    logFn(
      `[GUARDRAIL VIOLATION] ${violation.invariant}`,
      {
        checkpoint,
        gameId: result.gameId,
        message: violation.message,
        actual: violation.actualValue,
        limit: violation.limitValue,
        severity: violation.severity,
      }
    );
  });

  // Summary
  const errorCount = result.violations.filter((v) => v.severity === "error").length;
  const warningCount = result.violations.filter((v) => v.severity === "warning").length;

  if (errorCount > 0) {
    console.error(
      `[GUARDRAIL] ✗ ${checkpoint} FAILED`,
      {
        gameId: result.gameId,
        errors: errorCount,
        warnings: warningCount,
        metrics: result.metrics,
      }
    );
  } else {
    console.warn(
      `[GUARDRAIL] ⚠ ${checkpoint} passed with warnings`,
      {
        gameId: result.gameId,
        warnings: warningCount,
        metrics: result.metrics,
      }
    );
  }
}

// =============================================================================
// CONVENIENCE HOOKS
// =============================================================================

/**
 * React hook for guardrail validation.
 *
 * Use in components to validate blocks on render.
 *
 * @example
 * function MyComponent({ blocks, gameId }) {
 *   const guardrailResult = useGuardrails(blocks, gameId);
 *
 *   if (!guardrailResult.passed) {
 *     // Handle error state
 *   }
 *
 *   return <div>...</div>;
 * }
 */
export function useGuardrails(
  blocks: NarrativeBlock[],
  gameId: number | null
): GuardrailResult {
  // Validate on every render (memoization would hide violations)
  return validateBlocksPreRender(blocks, gameId);
}
