"""Celery task for async narrative quality grading (ISSUE-045).

Tier 1 (rule-based) and Tier 2 (LLM scorer) both run within this task so that
neither blocks the HTTP pipeline handler.  The task is dispatched by
finalize_moments.py immediately after the flow is persisted to the DB.
"""

from __future__ import annotations

import logging

from celery import shared_task

from ..celery_app import DEFAULT_QUEUE
from ..logging import logger as scraper_logger

logger = logging.getLogger(__name__)


@shared_task(
    name="grade_flow_task",
    bind=True,
    queue=DEFAULT_QUEUE,
    max_retries=2,
    default_retry_delay=60,
)
def grade_flow_task(
    self,
    flow_id: int,
    sport: str,
    game_id: int,
    is_template_fallback: bool = False,
) -> dict:
    """Grade a persisted game flow using the 3-tier quality grader.

    Args:
        flow_id: PK of the SportsGameFlow record.
        sport: League code (e.g. "NBA").
        game_id: PK of the associated SportsGame (used to fetch team/score data).
        is_template_fallback: True when the flow was generated by the deterministic
            template path; the grader is a no-op in that case.

    Returns:
        Dict with grader result summary, or {"skipped": True} for template flows.
    """
    import redis

    from ..config import settings
    from ..db import db_models, get_session
    from ..pipeline.grader import GraderResult, grade_flow

    if is_template_fallback:
        scraper_logger.info(
            "grade_flow_task_skip_template",
            extra={"flow_id": flow_id, "sport": sport},
        )
        return {"skipped": True, "reason": "template_fallback"}

    # Fetch flow + game data from DB
    blocks: list[dict] = []
    game_data: dict = {}
    try:
        with get_session() as session:
            flow = session.get(db_models.SportsGameFlow, flow_id)
            if flow is None:
                scraper_logger.warning(
                    "grade_flow_task_flow_not_found",
                    extra={"flow_id": flow_id},
                )
                return {"skipped": True, "reason": "flow_not_found"}

            blocks = flow.blocks_json or []

            game = session.get(db_models.SportsGame, game_id)
            if game:
                home_team = ""
                away_team = ""
                # Prefer full team name from relationships when loaded; fall back to game fields
                if hasattr(game, "home_team") and game.home_team:
                    home_team = getattr(game.home_team, "full_name", "") or ""
                if hasattr(game, "away_team") and game.away_team:
                    away_team = getattr(game.away_team, "full_name", "") or ""
                game_data = {
                    "sport": sport,
                    "home_team": home_team,
                    "away_team": away_team,
                    "home_score": game.home_score,
                    "away_score": game.away_score,
                }
    except Exception:
        logger.warning(
            "grade_flow_task_db_fetch_failed",
            exc_info=True,
            extra={"flow_id": flow_id},
        )
        raise self.retry(exc=None)

    if not blocks:
        scraper_logger.warning(
            "grade_flow_task_empty_blocks",
            extra={"flow_id": flow_id},
        )
        return {"skipped": True, "reason": "empty_blocks"}

    # Connect to Redis for Tier 2 cache
    try:
        redis_client = redis.from_url(settings.redis_url, decode_responses=True)
    except Exception:
        logger.warning("grade_flow_task_redis_connect_failed", exc_info=True)
        redis_client = None  # type: ignore[assignment]

    # Run grader (Tier 1 + Tier 2)
    result: GraderResult | None = grade_flow(
        flow_id=flow_id,
        sport=sport,
        blocks=blocks,
        game_data=game_data,
        redis_client=redis_client,
        is_template_fallback=False,
    )

    if result is None:
        return {"skipped": True, "reason": "grader_returned_none"}

    # Persist combined score and emit OTel metric
    try:
        with get_session() as session:
            flow = session.get(db_models.SportsGameFlow, flow_id)
            if flow is not None:
                flow.quality_score = result.combined_score
                session.flush()
    except Exception:
        logger.warning(
            "grade_flow_task_score_persist_failed",
            exc_info=True,
            extra={"flow_id": flow_id, "score": result.combined_score},
        )

    # OTel: emit per-tier and combined histogram values
    try:
        from app.services.pipeline.metrics import record_flow_quality_score  # type: ignore

        record_flow_quality_score(sport=sport, tier="tier1", score=result.tier1.score)
        if result.tier2 is not None:
            record_flow_quality_score(sport=sport, tier="tier2", score=result.tier2.score)
        record_flow_quality_score(sport=sport, tier="combined", score=result.combined_score)
    except Exception:
        logger.debug("grade_flow_task_otel_emit_failed", exc_info=True)

    # Tier 3: escalate flows below the threshold
    if result.escalated:
        _escalate_flow(result, game_id=game_id)

    scraper_logger.info(
        "grade_flow_task_complete",
        extra={
            "flow_id": flow_id,
            "sport": sport,
            "combined_score": result.combined_score,
            "escalated": result.escalated,
            "tier1_score": result.tier1.score,
            "tier2_score": result.tier2.score if result.tier2 else None,
            "cache_hit": result.tier2.cache_hit if result.tier2 else None,
        },
    )

    return {
        "flow_id": flow_id,
        "sport": sport,
        "combined_score": result.combined_score,
        "tier1_score": result.tier1.score,
        "tier2_score": result.tier2.score if result.tier2 else None,
        "tier2_cache_hit": result.tier2.cache_hit if result.tier2 else None,
        "escalated": result.escalated,
        "tier1_failures": result.tier1.failures,
    }


def _escalate_flow(result: "GraderResult", game_id: int) -> None:
    """Write a quality_review_queue row for a flow that scored below threshold."""
    from ..db import db_models, get_session

    tier_breakdown = {
        "tier1": {
            "score": result.tier1.score,
            "failures": result.tier1.failures,
            "checks": result.tier1.checks,
        },
        "tier2": {
            "score": result.tier2.score if result.tier2 else None,
            "rubric": result.tier2.rubric if result.tier2 else None,
            "cache_hit": result.tier2.cache_hit if result.tier2 else None,
        },
    }

    try:
        from app.db.quality_review import QualityReviewQueue  # type: ignore

        with get_session() as session:
            # Upsert: if a pending row already exists for this flow, update it
            existing = (
                session.query(QualityReviewQueue)
                .filter(
                    QualityReviewQueue.flow_id == result.flow_id,
                    QualityReviewQueue.status == "pending",
                )
                .first()
            )
            if existing:
                existing.combined_score = result.combined_score
                existing.tier1_score = result.tier1.score
                existing.tier2_score = result.tier2.score if result.tier2 else None
                existing.tier_breakdown = tier_breakdown
            else:
                row = QualityReviewQueue(
                    flow_id=result.flow_id,
                    game_id=game_id,
                    sport=result.sport,
                    combined_score=result.combined_score,
                    tier1_score=result.tier1.score,
                    tier2_score=result.tier2.score if result.tier2 else None,
                    tier_breakdown=tier_breakdown,
                    status="pending",
                )
                session.add(row)
            session.flush()

        logger.info(
            "grade_flow_escalated",
            extra={
                "flow_id": result.flow_id,
                "sport": result.sport,
                "combined_score": result.combined_score,
            },
        )
    except Exception:
        logger.warning(
            "grade_flow_escalation_failed",
            exc_info=True,
            extra={"flow_id": result.flow_id},
        )
