"""Celery task for async narrative quality grading (ISSUE-045).

Tier 1 (rule-based) and Tier 2 (LLM scorer) both run within this task so that
neither blocks the HTTP pipeline handler.  The task is dispatched by
finalize_moments.py immediately after the flow is persisted to the DB.
"""

from __future__ import annotations

import logging

from celery import shared_task

from ..celery_app import DEFAULT_QUEUE
from ..logging import logger as scraper_logger

logger = logging.getLogger(__name__)


@shared_task(
    name="grade_flow_task",
    bind=True,
    queue=DEFAULT_QUEUE,
    max_retries=2,
    default_retry_delay=60,
)
def grade_flow_task(
    self,
    flow_id: int,
    sport: str,
    game_id: int,
    is_template_fallback: bool = False,
    regen_attempt: int = 0,
) -> dict:
    """Grade a persisted game flow using the 3-tier quality grader.

    After grading, the result is passed through the quality gate
    (apply_grade_gate).  Low-scoring flows enqueue a regen attempt via
    regen_flow_task; a second failure applies template blocks inline and
    escalates the flow to the human review queue.

    Args:
        flow_id: PK of the SportsGameFlow record.
        sport: League code (e.g. "NBA").
        game_id: PK of the associated SportsGame (used to fetch team/score data).
        is_template_fallback: True when the flow was generated by the deterministic
            template path; the grader is a no-op in that case.
        regen_attempt: Number of regen attempts already completed for this game.
            0 = first pipeline pass; 1 = first regen (triggers template_fallback
            if still below threshold).

    Returns:
        Dict with grader result summary, or {"skipped": True} for template flows.
    """
    import redis

    from ..config import settings
    from ..db import db_models, get_session
    from ..pipeline.grader import GraderResult, grade_flow

    if is_template_fallback:
        scraper_logger.info(
            "grade_flow_task_skip_template",
            extra={"flow_id": flow_id, "sport": sport},
        )
        return {"skipped": True, "reason": "template_fallback"}

    # Fetch flow + game data from DB
    blocks: list[dict] = []
    game_data: dict = {}
    try:
        with get_session() as session:
            flow = session.get(db_models.SportsGameFlow, flow_id)
            if flow is None:
                scraper_logger.warning(
                    "grade_flow_task_flow_not_found",
                    extra={"flow_id": flow_id},
                )
                return {"skipped": True, "reason": "flow_not_found"}

            blocks = flow.blocks_json or []

            game = session.get(db_models.SportsGame, game_id)
            if game:
                home_team = ""
                away_team = ""
                # Prefer full team name from relationships when loaded; fall back to game fields
                if hasattr(game, "home_team") and game.home_team:
                    home_team = getattr(game.home_team, "full_name", "") or ""
                if hasattr(game, "away_team") and game.away_team:
                    away_team = getattr(game.away_team, "full_name", "") or ""
                game_data = {
                    "sport": sport,
                    "home_team": home_team,
                    "away_team": away_team,
                    "home_score": game.home_score,
                    "away_score": game.away_score,
                }
    except Exception:
        logger.warning(
            "grade_flow_task_db_fetch_failed",
            exc_info=True,
            extra={"flow_id": flow_id},
        )
        raise self.retry(exc=None)

    if not blocks:
        scraper_logger.warning(
            "grade_flow_task_empty_blocks",
            extra={"flow_id": flow_id},
        )
        return {"skipped": True, "reason": "empty_blocks"}

    # Connect to Redis for Tier 2 cache
    try:
        redis_client = redis.from_url(settings.redis_url, decode_responses=True)
    except Exception:
        logger.warning("grade_flow_task_redis_connect_failed", exc_info=True)
        redis_client = None  # type: ignore[assignment]

    # Run grader (Tier 1 + Tier 2)
    result: GraderResult | None = grade_flow(
        flow_id=flow_id,
        sport=sport,
        blocks=blocks,
        game_data=game_data,
        redis_client=redis_client,
        is_template_fallback=False,
    )

    if result is None:
        return {"skipped": True, "reason": "grader_returned_none"}

    # Persist combined score and emit OTel metric
    try:
        with get_session() as session:
            flow = session.get(db_models.SportsGameFlow, flow_id)
            if flow is not None:
                flow.quality_score = result.combined_score
                session.flush()
    except Exception:
        logger.warning(
            "grade_flow_task_score_persist_failed",
            exc_info=True,
            extra={"flow_id": flow_id, "score": result.combined_score},
        )

    # OTel: emit per-tier and combined histogram values
    try:
        from app.services.pipeline.metrics import record_flow_quality_score  # type: ignore

        record_flow_quality_score(sport=sport, tier="tier1", score=result.tier1.score)
        if result.tier2 is not None:
            record_flow_quality_score(sport=sport, tier="tier2_haiku", score=result.tier2.score)
        if result.tier2_sonnet is not None:
            record_flow_quality_score(sport=sport, tier="tier2_sonnet", score=result.tier2_sonnet.score)
        record_flow_quality_score(sport=sport, tier="combined", score=result.combined_score)
    except Exception:
        logger.warning("grade_flow_task_otel_emit_failed", exc_info=True)

    # ── Quality gate (ISSUE-053) ─────────────────────────────────────────────
    # Apply the grade gate.  Low-scoring flows are not left published; instead
    # a regen is dispatched (first failure) or templates are applied (second).
    from ..pipeline.grade_gate import apply_grade_gate

    gate = apply_grade_gate(result, regen_attempt=regen_attempt)

    if gate.action == "regen":
        _dispatch_regen(
            game_id=game_id,
            sport=sport,
            failure_reasons=gate.failures,
            regen_attempt=regen_attempt,
        )
    elif gate.action == "template_fallback":
        _apply_template_fallback(
            flow_id=flow_id,
            game_id=game_id,
            sport=sport,
        )
        # Escalate to human review after template fallback; pass result for
        # tier breakdown even though the blocks have been replaced.
        _escalate_flow(result, game_id=game_id, reason="template_fallback")
    else:
        # gate.action == "publish": normal path.
        # Escalate for human review if score is below ESCALATION_THRESHOLD
        # even when the gate itself passes (monitors borderline flows).
        if result.escalated:
            _escalate_flow(result, game_id=game_id, reason="low_combined_score")

    # Human review queue: Sonnet ambiguous after regen.
    # When Haiku was uncertain (ambiguous band), Sonnet was invoked, and Sonnet is
    # ALSO in the ambiguous band on a regen attempt — queue for human review
    # regardless of gate action (the model couldn't resolve the quality signal).
    from ..pipeline.grader import SONNET_AMBIGUOUS_BAND_HIGH, SONNET_AMBIGUOUS_BAND_LOW

    if (
        result.haiku_ambiguous
        and result.tier2_sonnet is not None
        and SONNET_AMBIGUOUS_BAND_LOW <= result.tier2_sonnet.score <= SONNET_AMBIGUOUS_BAND_HIGH
        and regen_attempt >= 1
    ):
        _escalate_flow(result, game_id=game_id, reason="sonnet_ambiguous_after_regen")

    scraper_logger.info(
        "grade_flow_task_complete",
        extra={
            "flow_id": flow_id,
            "sport": sport,
            "combined_score": result.combined_score,
            "escalated": result.escalated,
            "gate_action": gate.action,
            "regen_attempt": regen_attempt,
            "tier1_score": result.tier1.score,
            "tier2_haiku_score": result.tier2.score if result.tier2 else None,
            "tier2_haiku_cache_hit": result.tier2.cache_hit if result.tier2 else None,
            "haiku_ambiguous": result.haiku_ambiguous,
            "tier2_sonnet_score": result.tier2_sonnet.score if result.tier2_sonnet else None,
            "tier2_sonnet_cache_hit": result.tier2_sonnet.cache_hit if result.tier2_sonnet else None,
        },
    )

    return {
        "flow_id": flow_id,
        "sport": sport,
        "combined_score": result.combined_score,
        "tier1_score": result.tier1.score,
        "tier2_haiku_score": result.tier2.score if result.tier2 else None,
        "tier2_haiku_cache_hit": result.tier2.cache_hit if result.tier2 else None,
        "haiku_ambiguous": result.haiku_ambiguous,
        "tier2_sonnet_score": result.tier2_sonnet.score if result.tier2_sonnet else None,
        "tier2_sonnet_cache_hit": result.tier2_sonnet.cache_hit if result.tier2_sonnet else None,
        "escalated": result.escalated,
        "gate_action": gate.action,
        "regen_attempt": regen_attempt,
        "tier1_failures": result.tier1.failures,
    }


def _escalate_flow(result: "GraderResult", game_id: int, reason: str = "low_combined_score") -> None:
    """Write a quality_review_queue row for a flow that scored below threshold."""
    from ..db import db_models, get_session

    tier_breakdown: dict = {
        "tier1": {
            "score": result.tier1.score,
            "failures": result.tier1.failures,
            "checks": result.tier1.checks,
        },
        "tier2_haiku": {
            "score": result.tier2.score if result.tier2 else None,
            "rubric": result.tier2.rubric if result.tier2 else None,
            "cache_hit": result.tier2.cache_hit if result.tier2 else None,
        },
        "tier2_sonnet": {
            "score": result.tier2_sonnet.score if result.tier2_sonnet else None,
            "rubric": result.tier2_sonnet.rubric if result.tier2_sonnet else None,
            "cache_hit": result.tier2_sonnet.cache_hit if result.tier2_sonnet else None,
        } if result.tier2_sonnet is not None else None,
        "haiku_ambiguous": result.haiku_ambiguous,
        "reason": reason,
    }

    try:
        from app.db.quality_review import QualityReviewQueue  # type: ignore

        with get_session() as session:
            # Upsert: if a pending row already exists for this flow, update it
            existing = (
                session.query(QualityReviewQueue)
                .filter(
                    QualityReviewQueue.flow_id == result.flow_id,
                    QualityReviewQueue.status == "pending",
                )
                .first()
            )
            if existing:
                existing.combined_score = result.combined_score
                existing.tier1_score = result.tier1.score
                existing.tier2_score = result.tier2.score if result.tier2 else None
                existing.tier_breakdown = tier_breakdown
            else:
                row = QualityReviewQueue(
                    flow_id=result.flow_id,
                    game_id=game_id,
                    sport=result.sport,
                    combined_score=result.combined_score,
                    tier1_score=result.tier1.score,
                    tier2_score=result.tier2.score if result.tier2 else None,
                    tier_breakdown=tier_breakdown,
                    status="pending",
                )
                session.add(row)
            session.flush()

        logger.info(
            "grade_flow_escalated",
            extra={
                "flow_id": result.flow_id,
                "sport": result.sport,
                "combined_score": result.combined_score,
            },
        )
    except Exception:
        logger.warning(
            "grade_flow_escalation_failed",
            exc_info=True,
            extra={"flow_id": result.flow_id},
        )


def _dispatch_regen(
    game_id: int,
    sport: str,
    failure_reasons: list[str],
    regen_attempt: int,
) -> None:
    """Enqueue regen_flow_task with structured failure context."""
    try:
        from .regen_flow_task import regen_flow_task

        regen_flow_task.apply_async(
            kwargs={
                "game_id": game_id,
                "sport": sport,
                "failure_reasons": failure_reasons,
                "regen_attempt": regen_attempt,
            },
        )
        logger.info(
            "grade_gate_regen_dispatched",
            extra={
                "game_id": game_id,
                "sport": sport,
                "failure_count": len(failure_reasons),
                "regen_attempt": regen_attempt,
            },
        )
    except Exception:
        logger.warning(
            "grade_gate_regen_dispatch_failed",
            exc_info=True,
            extra={"game_id": game_id},
        )


def _apply_template_fallback(
    flow_id: int,
    game_id: int,
    sport: str,
) -> None:
    """Overwrite a low-quality flow with deterministic template blocks.

    Fetches game data from the DB, renders template blocks using the
    scraper-side TemplateEngine, and updates the SportsGameFlow record
    in-place.  Called when the gate decides template_fallback (i.e. the
    flow has already consumed its one permitted regen attempt).
    """
    try:
        from ..db import db_models, get_session
        from ..pipeline.templates import GameMiniBox, TemplateEngine

        with get_session() as session:
            game = session.get(db_models.SportsGame, game_id)
            flow = session.get(db_models.SportsGameFlow, flow_id)

            if game is None or flow is None:
                logger.warning(
                    "grade_gate_template_fallback_missing",
                    extra={"flow_id": flow_id, "game_id": game_id},
                )
                return

            home_team = ""
            away_team = ""
            if hasattr(game, "home_team") and game.home_team:
                home_team = getattr(game.home_team, "full_name", "") or getattr(
                    game.home_team, "name", ""
                ) or ""
            if hasattr(game, "away_team") and game.away_team:
                away_team = getattr(game.away_team, "full_name", "") or getattr(
                    game.away_team, "name", ""
                ) or ""

            mini_box = GameMiniBox(
                home_team=home_team or "Home Team",
                away_team=away_team or "Away Team",
                home_score=int(game.home_score or 0),
                away_score=int(game.away_score or 0),
                sport=sport,
                has_overtime=False,
                total_moments=int(flow.moment_count or 0),
            )
            template_blocks = TemplateEngine.render(sport, mini_box)

            flow.blocks_json = template_blocks
            flow.block_count = len(template_blocks)
            flow.flow_source = "TEMPLATE"
            session.flush()

        logger.info(
            "grade_gate_template_fallback_applied",
            extra={
                "flow_id": flow_id,
                "game_id": game_id,
                "sport": sport,
                "block_count": len(template_blocks),
            },
        )
    except Exception:
        logger.warning(
            "grade_gate_template_fallback_failed",
            exc_info=True,
            extra={"flow_id": flow_id, "game_id": game_id},
        )
