apiVersion: 1

datasources:
  - name: SportsDB
    type: postgres
    uid: sports-postgres
    url: postgres:5432
    user: ${POSTGRES_USER:-sports}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-sports}
    jsonData:
      database: ${POSTGRES_DB:-sports}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
